### ISSUE TITLE
SkipLabel with multiple labels?

### ISSUE THREAD

**Issue by mathomp4** [dangoslen/changelog-enforcer#29]
Another question for @dangoslen: does the enforcer allow multiple labels to skip the changelog? 

I currently have my repo using something a la "trivial" but I might also want a label that is "skip changelog" for those times when we are doing an operation which isn't trivial, but is so structural that the changelog isn't needed (we have multiple protected branches which makes GitHub "fun" at times).

**Comment by dangoslen** [comment]
Hey @mathomp4. It currently does not support multiple labels. 

My reasoning for that is that a pull request in GitHub can be tagged with multiple labels, so instead of making it more complicated to handle multiple labels in the enforcer, you can just add the label to a pull request you want it skipped on.

I agree that means you might have to put additional labels on a pull request.

If you wanted to take a stab at implementing it though, I'd be happy for a contribution! It would just need to be backwards compatible with the existing property.

**Comment by fschmager** [comment]
The [automerge gh action](https://github.com/pascalgn/automerge-action) does this nicely, by allowing comma separated labels (including exclusions via `!`).

It [uses an env var](https://github.com/pascalgn/automerge-action/blob/2b9a4d42e7410a9917eed3a5ba2b0add1db4f39e/lib/common.js#L106) but inputs should be similar.

From their [usage documentation](https://github.com/pascalgn/automerge-action#configuration):
> `MERGE_LABELS`: The labels that need to be present for a pull request to be
  merged (using `MERGE_METHOD`). The default value is `automerge`.

>  This option can be a comma-separated list of labels that will be checked. All
  labels in the list need to be present, otherwise the pull request will be
  skipped (until all labels are present). Labels prefixed with an exclamation
  mark (`!`) will block a pull request from being merged, when present.

>  For example, when `automerge,!wip,!work in progress` is given,
  any pull requests with the labels `wip` or `work in progress` and any pull
  requests _without_ the label `automerge` will not be merged.
  Blocking labels take precedence, so if a pull request has both labels
  `wip` and `automerge`, it will not be merged.

>  When an empty string (`""`) is given, all pull requests will be merged.

The [actual parsing code](https://github.com/pascalgn/automerge-action/blob/2b9a4d42e7410a9917eed3a5ba2b0add1db4f39e/lib/common.js#L60-L70) is also straightforward.

Re backcompat, a new input/env var (e.g. `skipLabels`) could be added and be mutually exclusive with the old input/env var (`skipLabel`). Though allowing negative matches (`!`-prefixed label names) causes double negatives, e.g. `skipLabels: !do-enforce-changelog`. Maybe it should be `enforceLabels` defaulting to `""` implying all labels, to always enforce.

**Comment by dangoslen** [comment]
I don't know if I like the `enforceLabels` idea because the intent is the the majority of pull requests _should_ have the enforcer applied. The auto-merge action is a little more "opt-in" in how I view its use case.

Adding a `skipLabels` I think is the right first step.  I would want to avoid negating labels for the time being to avoid the double-negation as you mention too. 

All in all, because labels are (IMO) easy to add and remove, I would want to aim for keeping this action simpler.

**Comment by fschmager** [comment]
Fair enough wrt to simplicity. As soon as you start accepting multiple labels you have to think are they `AND` or `OR` labels. Skip if one of the labels is present or if all the labels are present.

**Comment by dangoslen** [comment]
@mathomp4 and @fschmager 

Pull request #54 should add this feature in as a new input variable. Have a look and provide any feedback you have - especially on documentation. A preview of the release notes that will be created is added as a comment.
